# Generated by Django 3.1.1 on 2020-09-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configitem',
            old_name='field',
            new_name='FTP_URL',
        ),
        migrations.RemoveField(
            model_name='configitem',
            name='value',
        ),
        migrations.AddField(
            model_name='configitem',
            name='JPGisChecked',
            field=models.BooleanField(default=False),
        ),
    ]
