# Generated by Django 3.1.1 on 2020-09-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0002_auto_20200903_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='configitem',
            name='GIFisChecked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configitem',
            name='NEFisChecked',
            field=models.BooleanField(default=False),
        ),
    ]
