# Generated by Django 3.1.1 on 2020-09-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0004_auto_20200903_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configitem',
            name='GIF',
        ),
        migrations.RemoveField(
            model_name='configitem',
            name='JPG',
        ),
        migrations.RemoveField(
            model_name='configitem',
            name='NEF',
        ),
        migrations.AddField(
            model_name='configitem',
            name='FileType_List',
            field=models.CharField(default='', max_length=250),
        ),
    ]
