# Generated by Django 3.1.1 on 2020-09-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0005_auto_20200903_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configitem',
            name='FTP_URL',
        ),
        migrations.AddField(
            model_name='configitem',
            name='DestDir',
            field=models.CharField(default='/NymeBox', max_length=20),
        ),
        migrations.AddField(
            model_name='configitem',
            name='FTPPassword',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='configitem',
            name='FTPUser',
            field=models.CharField(default='ftpuser', max_length=250),
        ),
        migrations.AddField(
            model_name='configitem',
            name='FtpURL',
            field=models.URLField(default='https://qlink.to/TREK3', max_length=250),
        ),
        migrations.AddField(
            model_name='configitem',
            name='SourceDir',
            field=models.CharField(default='/var/www/NymeBox/SDCARD/**', max_length=250),
        ),
        migrations.AlterField(
            model_name='configitem',
            name='FileType_List',
            field=models.CharField(default='*.GIF,*.JPG', max_length=250),
        ),
    ]
