# Generated by Django 3.1.1 on 2020-09-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0006_auto_20200904_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configitem',
            old_name='FileType_List',
            new_name='FileTypeList',
        ),
    ]
