# Generated by Django 3.1.1 on 2020-09-09 20:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0007_auto_20200904_1046'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='configitem',
            managers=[
                ('ProcMode', django.db.models.manager.Manager()),
            ],
        ),
    ]
