# Generated by Django 3.1.1 on 2020-09-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0008_auto_20200909_1505'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='configitem',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='configitem',
            name='ProcMode',
            field=models.CharField(db_index=True, default='TEST', max_length=30),
        ),
    ]
