# Generated by Django 3.1.1 on 2020-09-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0009_auto_20200909_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='configitem',
            name='ProcMode',
            field=models.CharField(db_index=True, default='TEST', max_length=30, primary_key=True, serialize=False),
        ),
    ]
