# Generated by Django 3.1.1 on 2020-09-09 21:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0010_auto_20200909_1638'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='configitem',
            managers=[
                ('Manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
