# Generated by Django 3.1.1 on 2020-09-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0011_auto_20200909_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configitem',
            name='FtpURL',
            field=models.CharField(default='TREK', max_length=250),
        ),
    ]
