# Generated by Django 3.1.1 on 2020-09-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0012_auto_20200910_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='configitem',
            name='LastLog',
            field=models.TextField(default=''),
        ),
    ]
