# Generated by Django 3.1.1 on 2020-09-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0013_configitem_lastlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='configitem',
            name='MovedFiles',
            field=models.TextField(default=''),
        ),
    ]
